// generated by Glue 8.0 Fix 8 build 2 (wsdl2java) on Wed Feb 10 12:05:46 IST 2016

package caf.war.OpenCAFAPP.wsclient.wsd.librarywsdl;

public class Book implements java.io.Serializable
  {
  private java.lang.String ISBN;
  private java.lang.String BOOK_NAME;
  private java.lang.String AUTHOR;
  private java.lang.String CATEGORY;
  private java.lang.Integer VERSIONS;

  public java.lang.String getISBN()
    {
    return ISBN;
    }

  public void setISBN( java.lang.String value )
    {
    this.ISBN = value;
    }

  public java.lang.String getBOOK_NAME()
    {
    return BOOK_NAME;
    }

  public void setBOOK_NAME( java.lang.String value )
    {
    this.BOOK_NAME = value;
    }

  public java.lang.String getAUTHOR()
    {
    return AUTHOR;
    }

  public void setAUTHOR( java.lang.String value )
    {
    this.AUTHOR = value;
    }

  public java.lang.String getCATEGORY()
    {
    return CATEGORY;
    }

  public void setCATEGORY( java.lang.String value )
    {
    this.CATEGORY = value;
    }

  public java.lang.Integer getVERSIONS()
    {
    return VERSIONS;
    }

  public void setVERSIONS( java.lang.Integer value )
    {
    this.VERSIONS = value;
    }
  }
