// generated by Glue 8.0 Fix 8 build 2 (wsdl2java) on Wed Feb 10 12:05:46 IST 2016

package caf.war.OpenCAFAPP.wsclient.wsd.librarywsdl;

public class getLibraryBookVersionsResponse implements java.io.Serializable
  {
  private caf.war.OpenCAFAPP.wsclient.wsd.librarywsdl.Book[] libraryBooks;

  public caf.war.OpenCAFAPP.wsclient.wsd.librarywsdl.Book[] getLibraryBooks()
    {
    return libraryBooks;
    }

  public void setLibraryBooks( caf.war.OpenCAFAPP.wsclient.wsd.librarywsdl.Book[] value )
    {
    this.libraryBooks = value;
    }
  }
