// generated by Glue 8.0 Fix 8 build 2 (wsdl2java) on Wed Feb 10 12:05:46 IST 2016

package caf.war.OpenCAFAPP.wsclient.wsd.librarywsdl;

import electric.util.async.Async;

public interface IlibraryWSDL_PortType
  {
  public void insertBook( caf.war.OpenCAFAPP.wsclient.wsd.librarywsdl.insertBook insertBook , Async result );

  public caf.war.OpenCAFAPP.wsclient.wsd.librarywsdl.getLibraryBookVersionsResponse getLibraryBookVersions( caf.war.OpenCAFAPP.wsclient.wsd.librarywsdl.getLibraryBookVersions getLibraryBookVersions );
  }
