// generated by Glue 8.0 Fix 8 build 2 (wsdl2java) on Wed Feb 10 12:05:46 IST 2016

package caf.war.OpenCAFAPP.wsclient.wsd.librarywsdl;

import electric.registry.Registry;
import electric.registry.RegistryException;
import electric.util.Context;

public class libraryWSDLHelper
  {
  public static IlibraryWSDL_PortType bind()
    throws RegistryException
    {
    return bind( "file:/C:/Users/dpod/workspace98HQ/Electronic_Library/src/caf/war/OpenCAFAPP/wsclient/wsd/librarywsdl/libraryWSDL.wsdl" );
    }

  public static IlibraryWSDL_PortType bind( String url )
    throws RegistryException
    {
    return bind( url, new Context() );
    }

  public static IlibraryWSDL_PortType bind( String url , Context context )
    throws RegistryException
    {
    return (IlibraryWSDL_PortType) Registry.bind( url, IlibraryWSDL_PortType.class, context );
    }
  }
