// generated by Glue 8.0 Fix 8 build 2 (wsdl2java) on Wed Feb 10 12:05:46 IST 2016

package caf.war.OpenCAFAPP.wsclient.wsd.librarywsdl;

public class uploadFile implements java.io.Serializable
  {
  private java.lang.Object BOOK_DATE;

  public java.lang.Object getBOOK_DATE()
    {
    return BOOK_DATE;
    }

  public void setBOOK_DATE( java.lang.Object value )
    {
    this.BOOK_DATE = value;
    }
  }
